language: c

cache:
  apt: true
  directories:
    - mk/.cache

env:
  global:
    # Encrypted COVERITY_SCAN_TOKEN
    - secure: fFf+lgHUkycCUGXTpVCnSL8G+sI/Wr+lbm/9jdy6Lw19MF33E4eC8oln/0OZFrfWY4Xy1QC9jfVgdsYd1jeI+e+mtrVdUzBJPO2z6BN978KiNmQzgff8epkpQB0k9qbDAqsNmjSwShN3PaeOZTUHiusWg0PMCQRb3SokLhKplhk=    - AUTOQEMU_NICS=''
    - AUTOQEMU_NICS=''
  matrix:
    - TEMPLATE=arm/qemu
    - TEMPLATE=x86/qemu

before_install:
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo apt-get update -qq

# TODO make it template-specific
install:
  - sudo apt-get install -qq gcc-arm-none-eabi
  - sudo apt-get install -qq gcc-multilib
  - sudo apt-get install -qq u-boot-tools
  - sudo apt-get install -qq qemu qemu-system

before_script:
  - make confload-"$TEMPLATE"
  - sed -ie '/eth0/d' conf/start_script.inc  # FIXME
  - make buildgen  # Make as much as possible before the actual build step.

script:
  - make
  - ./scripts/continuous/run.sh "$TEMPLATE"

addons:
  coverity_scan:
    project:
      name: "embox/embox"
      description: "Build submitted via Travis CI"
    notification_email: eldar.abusalimov@gmail.com
    build_command_prepend: make confload-"$TEMPLATE" buildgen
    build_command: make
    branch_pattern: coverity_scan

notifications:
  slack:
    secure: ATPx+JnB3aMwuyXlJElYv47Z17o5h7rVN2xGOdwKyvuB0HKiGxkUfxAOK37CkLVTZ1i1Jozb1aoDGojTO+zmo4kCfKP3VXRLW9RTVhxt96MlUM0FCRed1bxi1A9rswpaEfWQXpuk9GjUPZOYgSK8D+IV63rhT5F9m4b3Z8WLkr0=
